//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipZon.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MobileLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MobileLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlipZon.Resources.Localization.MobileLabel", typeof(MobileLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        internal static string Add_Address {
            get {
                return ResourceManager.GetString("Add_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address Screen.
        /// </summary>
        internal static string Add_Address_Screen {
            get {
                return ResourceManager.GetString("Add_Address_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        internal static string Add_New_Address {
            get {
                return ResourceManager.GetString("Add_New_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To cart.
        /// </summary>
        internal static string Add_To_cart {
            get {
                return ResourceManager.GetString("Add_To_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address List Screen.
        /// </summary>
        internal static string Address_List_Screen {
            get {
                return ResourceManager.GetString("Address_List_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an Account?.
        /// </summary>
        internal static string Already_have_an_Account {
            get {
                return ResourceManager.GetString("Already_have_an_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Screen.
        /// </summary>
        internal static string Cart_Screen {
            get {
                return ResourceManager.GetString("Cart_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string Contact_Details {
            get {
                return ResourceManager.GetString("Contact Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliver to this addrees.
        /// </summary>
        internal static string Deliver_to_this_addrees {
            get {
                return ResourceManager.GetString("Deliver_to_this_addrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Fee.
        /// </summary>
        internal static string Delivery_Fee {
            get {
                return ResourceManager.GetString("Delivery_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have the Account.
        /// </summary>
        internal static string Dont_have_the_Account {
            get {
                return ResourceManager.GetString("Dont_have_the_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door No.
        /// </summary>
        internal static string Door_No {
            get {
                return ResourceManager.GetString("Door_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Address.
        /// </summary>
        internal static string Edit_Address {
            get {
                return ResourceManager.GetString("Edit_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Confirm Password.
        /// </summary>
        internal static string Enter_Confirm_Password {
            get {
                return ResourceManager.GetString("Enter_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile No.
        /// </summary>
        internal static string Enter_Mobile_No {
            get {
                return ResourceManager.GetString("Enter_Mobile_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Address.
        /// </summary>
        internal static string Enter_Your_Address {
            get {
                return ResourceManager.GetString("Enter_Your_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Door No.
        /// </summary>
        internal static string Enter_Your_Door_No {
            get {
                return ResourceManager.GetString("Enter_Your_Door_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        internal static string Enter_Your_Email {
            get {
                return ResourceManager.GetString("Enter_Your_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Name.
        /// </summary>
        internal static string Enter_your_Name {
            get {
                return ResourceManager.GetString("Enter_your_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Password.
        /// </summary>
        internal static string Enter_your_Password {
            get {
                return ResourceManager.GetString("Enter_your_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Pincode.
        /// </summary>
        internal static string Enter_Your_Pincode {
            get {
                return ResourceManager.GetString("Enter_Your_Pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Zon.
        /// </summary>
        internal static string FlipZon {
            get {
                return ResourceManager.GetString("FlipZon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hang on Loading More Products.
        /// </summary>
        internal static string Hang_on_Loading_More_Products {
            get {
                return ResourceManager.GetString("Hang_on_Loading_More_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string Mobile_No {
            get {
                return ResourceManager.GetString("Mobile_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Popular.
        /// </summary>
        internal static string Most_Popular {
            get {
                return ResourceManager.GetString("Most_Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode.
        /// </summary>
        internal static string Pincode {
            get {
                return ResourceManager.GetString("Pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string Place_Order {
            get {
                return ResourceManager.GetString("Place_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details Screen.
        /// </summary>
        internal static string Product_Details_Screen {
            get {
                return ResourceManager.GetString("Product_Details_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Screen.
        /// </summary>
        internal static string Products_Screen {
            get {
                return ResourceManager.GetString("Products_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Address.
        /// </summary>
        internal static string Save_Address {
            get {
                return ResourceManager.GetString("Save_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save For Later.
        /// </summary>
        internal static string Save_For_Later {
            get {
                return ResourceManager.GetString("Save_For_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Products.
        /// </summary>
        internal static string Search_Products {
            get {
                return ResourceManager.GetString("Search_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Screen.
        /// </summary>
        internal static string Search_Screen {
            get {
                return ResourceManager.GetString("Search_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        internal static string See_More {
            get {
                return ResourceManager.GetString("See_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Sign_In {
            get {
                return ResourceManager.GetString("Sign_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
